baseURL = "https://japer-eng.netlify.com/"
languageCode = "jp"
title = "My activity log"
theme = "hyde"
# theme = "northendlab"
hasCJKLanguage = true
summaryLength = 20

[params]
author = "japer"
keywords = ["English","school","TOEFL","blog","study abroad"]
description = "My activity, especially for getting job, studying English and abroad"
ogp_thumb = "images/ogp_thumb.jpg"
twitter_auther = "@cookie_m0gum0gu"
# common_title = "TOEFL independent-writing topic: "